### ISSUE TITLE
[tidyeval] récupérer la taille d'un fichier

### ISSUE THREAD

**Issue by pachevalier** [joelgombin/banR#13]
Dans la fonction geocode_tbl() dans la branche tidyeval, pour le moment, on récupère la taille du fichier avec file.size(). Pour obtenir la taille du fichier dans une unité 'lisible par un humain', on peut utiliser la commande ([SO](https://stackoverflow.com/questions/29787452/how-do-i-quickly-convert-the-size-element-of-file-info-from-bytes-to-kb-mb-g)) : 

> utils:::format.object_size(file.size(tmp), "auto")

Mais quand on check le package, on obtient : 

> Unexported object imported by a ':::' call: ‘utils:::format.object_size’

Faudrait trouver un autre moyen d'afficher la taille du fichier en MB.

**Comment by joelgombin** [comment]
ou sinon importer et réexporter la commande ? Je ne sais pas si on peut le faire pour une fonction non exportée par son package.

**Comment by pachevalier** [comment]
J'ai bêtement repris le code https://github.com/joelgombin/banR/blob/tidyeval-dev/R/utils.R
