### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by dicorynia** [joelgombin/banR#16]
Merci pour ce paquet.

Sur un jeu-test j'ai :
```r
Writing tempfile to...C:\Users\xxx\AppData\Local\Temp\RtmpSS0T23\file83cd61558e.csv
If file is larger than 8 MB, it must be splitted
Size is : 15.7 Kb
SuccessOKSuccess: (200) OK
Warning: 1 parsing failure.
row # A tibble: 1 x 5 col     row                col               expected actual         file expected   <int>              <chr>                  <chr>  <chr>        <chr> actual 1   116 result_housenumber no trailing characters      B <raw vector> file # A tibble: 1 x 5

Warning message:
In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 2)
```
Je n'ai pas identifié les lignes responsables dans mes données mais en changeant les options de parsing de colonnes de la réponse dans la fonction `geocode_tbl` en : `result_housenumber = readr::col_character()` et `result_postcode = readr::col_character()`  ça passe.

Cordialement

**Comment by joelgombin** [comment]
En y pensant, c'est logique. On peut avoir des codes postaux corses, des bis, etc. Merci !

**Comment by dicorynia** [comment]
Merci aussi...

**Comment by dicorynia** [comment]
Bonjour
Il semble qu'il y ait eu une régression depuis...
Le dataframe retourné a les champs
* "result_postcode" et
* "result_housenumber"

à nouveau comme "int" au lieu de "chr"

Cordialement
