### ISSUE TITLE
Geocode cities instead of specific addresses

### ISSUE THREAD

**Issue by briatte** [joelgombin/banR#25]
Dear @joelgombin and @pachevalier 

Is there any way to get 'city-level' geocodes with `banR`, as with [`tidygeocoder::geo_osm`](https://github.com/jessecambon/tidygeocoder)?

It seems this was possible at some point, as in Joël's example in #6.

I basically want pseudo-centroids for city-level queries like "Lille, France", "Bondue, France" etc.

Hope you're both good!

**Comment by joelgombin** [comment]
I think that this is related to #24 and will be solved if I can implement it.

**Comment by joelgombin** [comment]
Anyway it does work at the moment, doesn't it?

See:

```r
banR::geocode("Lille")
```

You may want to then filter the results:

```r

banR::geocode("Lille") %>% 
  dplyr::filter(type %in% "municipality")
```

**Comment by briatte** [comment]
You are correct, twice -- #24 is a more elaborate version of my question, and yes, `banR` does what I want, but only if, I just realised, I do not append "France" to the query:

-  "Valserhône" finds the municipality
- "Valserhône France" finds only addresses

Thanks!

**Comment by joelgombin** [comment]
I guesd that's because the BAN is only about French adresses.

Le dim. 29 mars 2020 à 11:35, François Briatte <notifications@github.com> a
écrit :
