### ISSUE TITLE
Base url en https

### ISSUE THREAD

**Issue by a-alexandre** [joelgombin/banR#37]
Bonjour,

En regardant le code de `geocode_tbl` je me suis apperçu que la base_url est en http :

https://github.com/joelgombin/banR/blob/master/R/geocode_tbl.R#L66

Les exemples de l'api sont donnés en https : https://geo.api.gouv.fr/adresse

Je ne sais pas si ça influe beaucoup sur la confidentialité des données échangées avec l'API.

**Comment by pachevalier** [comment]
Merci. Il faut qu'on regarde.

**Comment by pachevalier** [comment]
J'ai corrigé.
