### ISSUE TITLE
reverse-geocoding

### ISSUE THREAD

**Issue by joelgombin** [joelgombin/banR#4]
We need to implement the reverse-geocoding option. @pachevalier, can you think of a dataset we could use as a test/example?

**Comment by pachevalier** [comment]
Maybe the geolocalisation of high schools : https://www.data.gouv.fr/s/resources/adresse-et-geolocalisation-des-etablissements-denseignement-du-premier-et-second-degres/community/20150116-105204/depp-etablissements-premier-et-second-degres-structures-administratives-education-avril-2014.csv 

https://www.data.gouv.fr/fr/datasets/adresse-et-geolocalisation-des-etablissements-denseignement-du-premier-et-second-degres/

I know that we have addresses data in another file but it's just an exercise.
