### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by pachevalier** [joelgombin/banR#7]
When trying to lint the code with the `lintr` package, I've got several warnings : 

- the variable `queryResults` should be lowercase
- the name of the package should also be lowercase !

Should we rename the package ? 

By the way, I think we need to think about the name of variables. 

I think it would be nice to have : 

- `geocode` : for geocoding a single address (ie using the one line API : http://adresse.data.gouv.fr/api/)
- `reverse_geocode` : for reverse geocoding a single point
- `geocode_df` or `geocode_csv` for geocoding a dataframe (ie the actual `ban_geocode`)
- `reverse_geocode_df` for reverse geocoding a dataframe

I think the ban prefix is useless since the name of the package is already banR.

**Comment by pachevalier** [comment]
- Forgot the comment about the name of the package. It's just that we need to put quotes around the name when using the `library()` function according to the lintr package.

**Comment by joelgombin** [comment]
Completely agree with your proposed naming scheme. I think `geocode_df` is better. 
The ban prefix was there to allow using the autocomplete feature in rstudio: you just type `ban` and rstudio suggests you all the funtions from the package. I kinda like it, but it can completely be dropped.

**Comment by pachevalier** [comment]
I've renamed the variable geocode_tbl(). It's more consistent with modern R syntax.
