### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by pachevalier** [joelgombin/banR#9]
I've just tried to refactor the code of the main function. The goal is just to make it more readable. 
My attempt is in the branch refactoring.

**Comment by joelgombin** [comment]
There's a mistake [here](https://github.com/joelgombin/banR/blob/refactoring/R/geocode_df.R#L107), right?

**Comment by pachevalier** [comment]
I've deleted the branches refactoring and refactoring-pac. The new branch is tidyeval. It uses tidy evaluation and define the new function geocode_tbl().
